//  Created by Cooper Du on 2012-12-03.
#import "CDMigration.h"
#import "CDDatabase.h"

@interface CDScriptBaseMigration : NSObject <CDMigration>

@property(readonly, strong, nonatomic) NSString *fileName;
@property(readonly, nonatomic) int ver;
@property(readonly, strong, nonatomic) NSString *upgradeScriptName;
@property(readonly, strong, nonatomic) NSString *downgradeScriptName;

@end

@implementation CDScriptBaseMigration

- (id) initWithFileName: (NSString*) fileName version: (int) version upgradeScriptName: (NSString*) upgradeScriptName downgradeScriptName: (NSString*) downgradeScriptName
{
    self = [super init];
    _fileName = fileName;
    _ver = version;
    _upgradeScriptName = upgradeScriptName;
    _downgradeScriptName = downgradeScriptName;
    return self;
}

- (int) version
{
    return _ver;
}

- (bool) upgrade: (CDDatabase*) db
{
    return [db executeUpdate: [NSString stringWithFormat: @"@%@:%@", _fileName, _upgradeScriptName]];
}

- (bool) downgrade: (CDDatabase*) db
{
    return [db executeUpdate: [NSString stringWithFormat: @"@%@:%@", _fileName, _downgradeScriptName]];
}

- (NSString*) description
{
    return @"Generated by CDScriptBaseMigration";
}

@end

@implementation CDMigrationBuilder

+ (NSArray*) migrationsByScriptFile: (NSString*) fileName atVersion: (int) version
{
    NSMutableArray *result = [NSMutableArray new];
    for (int i = 1; i <= version; ++i) {
        NSString *upgradeScriptName = [NSString stringWithFormat: @"upgrade_%d", i];
        NSString *downgradeScript = [NSString stringWithFormat: @"downgrade_%d", i];
        id<CDMigration> migration = [[CDScriptBaseMigration new] initWithFileName: fileName version: i upgradeScriptName:upgradeScriptName downgradeScriptName: downgradeScript];
        [result addObject: migration];
    }
    return [NSArray arrayWithArray: result];
}

@end
